'use client';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: `By accessing or using the YAKK Studios platform at yakkstudios.xyz, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use this platform. Your continued use of the platform constitutes ongoing acceptance of any updates to these terms.`,
  },
  {
    title: '2. Not Financial Advice',
    body: `Nothing on this platform constitutes financial, investment, legal, or tax advice. YAKK Studios is not a registered broker, financial adviser, investment manager, or regulated financial institution in any jurisdiction. All content, tools, signals, and analytics provided are for informational and educational purposes only. You should consult a qualified professional before making any financial or investment decisions.`,
  },
  {
    title: '3. $YST Token — Utility Token',
    body: `The $YST token is a utility token on the Solana blockchain. It is not a security, equity, share, bond, or any regulated financial instrument. Holding $YST does not grant ownership of YAKK Studios, its assets, intellectual property, or future revenues. $YST is used solely to access platform features, participate in community activities, and engage with token-gated tools. YAKK Studios makes no guarantees regarding the market value, liquidity, or future utility of $YST.`,
  },
  {
    title: '4. Token-Gating — Access, Not Ownership',
    body: `Certain platform features require holding a minimum balance of $YST tokens. This token-gating model grants temporary access to those features for the duration of your holding period. It does not confer any ownership stake, equity interest, profit-sharing rights, or governance rights in YAKK Studios or its operations. Access may be modified, expanded, or restricted at any time at the sole discretion of YAKK Studios.`,
  },
  {
    title: '5. Non-Custodial Platform',
    body: `YAKK Studios does not custody, hold, manage, or control your funds, tokens, or private keys at any point. All transactions are executed directly on-chain via your connected wallet. You are solely responsible for the security of your wallet, seed phrase, and private keys. YAKK Studios has no ability to recover lost funds or reverse on-chain transactions.`,
  },
  {
    title: '6. AI Features — Experimental',
    body: `AI-powered features including YAKK Coach and YAKK Trader are experimental and provided on an as-is basis. Outputs from these tools are generated by large language models and are not verified, audited, or guaranteed for accuracy. They do not constitute investment advice, trading signals, or financial recommendations. You assume all risk when acting on any AI-generated content. YAKK Studios is not liable for any losses arising from use of AI features.`,
  },
  {
    title: '7. User Assumption of Risk',
    body: `You acknowledge and agree that participating in cryptocurrency markets and interacting with blockchain protocols carries significant risk, including the total loss of funds. On-chain transactions are irreversible. Smart contracts may contain bugs. Token prices are highly volatile. By using this platform, you confirm that you understand these risks and assume full responsibility for all on-chain actions taken from your wallet.`,
  },
  {
    title: '8. Limitation of Liability',
    body: `To the fullest extent permitted by applicable law, YAKK Studios, its founders, contributors, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of — or inability to use — this platform. This includes, without limitation, losses arising from transaction errors, smart contract failures, market volatility, platform downtime, or reliance on any content published on the platform.`,
  },
  {
    title: '9. Platform Changes',
    body: `YAKK Studios reserves the right to add, modify, suspend, or remove any feature, tool, or section of the platform at any time without notice. Token-gated features, access tiers, and $YST balance requirements may change. Continued use of the platform after any changes constitutes your acceptance of those changes.`,
  },
  {
    title: '10. Governing Law',
    body: `These Terms of Service are governed by and construed in accordance with the laws of Scotland, United Kingdom. Any disputes arising from or in connection with these terms shall be subject to the exclusive jurisdiction of the courts of Scotland. YAKK Studios is primarily operated from Scotland, UK, with secondary operations based in Portugal.`,
  },
  {
    title: '11. Contact',
    body: `If you have any questions about these Terms of Service, you can contact us at shyfts@yakkstudios.xyz.`,
    isContact: true,
  },
];

export default function Terms() {
  return (
    <div className="sec-pad" style={{ maxWidth: 800 }}>
      <div className="sec-eyebrow">LEGAL</div>
      <h2 className="sec-title">Terms of Service</h2>
      <div className="sec-bar" />

      <p style={{ fontSize: 12, color: 'var(--muted)', marginBottom: 32, lineHeight: 1.7 }}>
        Please read these terms carefully before using the YAKK Studios platform. By accessing yakkstudios.xyz, you agree to be bound by the following terms and conditions.
      </p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        {SECTIONS.map((sec, i) => (
          <div
            key={i}
            className="card"
            style={{ marginBottom: 8, borderLeft: '3px solid var(--pink)' }}
          >
            <h3 style={{
              fontFamily: 'var(--font-heading)',
              fontWeight: 700,
              fontSize: 13,
              color: 'var(--text)',
              marginBottom: 10,
              letterSpacing: 0.3,
            }}>
              {sec.title}
            </h3>
            <p style={{
              fontSize: 12,
              color: 'var(--muted)',
              lineHeight: 1.75,
              margin: 0,
            }}>
              {sec.isContact ? (
                <>
                  If you have any questions about these Terms of Service, you can contact us at{' '}
                  <a
                    href="mailto:shyfts@yakkstudios.xyz"
                    style={{ color: 'var(--pink)', textDecoration: 'underline' }}
                  >
                    shyfts@yakkstudios.xyz
                  </a>
                  .
                </>
              ) : (
                sec.body
              )}
            </p>
          </div>
        ))}
      </div>

      <div style={{
        marginTop: 24,
        padding: '14px 18px',
        background: 'rgba(224, 96, 126, 0.07)',
        border: '1px solid rgba(224, 96, 126, 0.25)',
        borderRadius: 8,
      }}>
        <p style={{ fontSize: 11, color: 'var(--muted)', lineHeight: 1.65, margin: 0 }}>
          <span style={{ color: 'var(--pink)', fontWeight: 700 }}>DISCLAIMER: </span>
          $YST is a utility token on the Solana blockchain. It is not a security or investment product. This platform does not provide financial advice. Crypto assets carry significant risk. Never invest more than you can afford to lose.
        </p>
      </div>

      <p style={{
        marginTop: 20,
        fontSize: 10,
        color: 'var(--dim)',
        fontFamily: 'var(--font-mono)',
        letterSpacing: '0.08em',
      }}>
        LAST UPDATED: APRIL 2026 · YAKK STUDIOS · SCOTLAND, UK &amp; PORTUGAL
      </p>
    </div>
  );
}
